version: '3.7'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    working_dir: /usr/share/nginx/html
    volumes:
      - ..:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/usr/share/nginx/html
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
